const plugin = require('tailwindcss/plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  // NativeWind v4 requires its preset; without it Metro's withNativeWind throws.
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bg: '#000000',
        s0: '#060607',
        s1: '#0B0B0D',
        s2: '#111114',
        s3: '#17171B',
        s4: '#1E1E23',
        ln: '#1A1A1F',
        ln2: '#26262C',
        ln3: '#33333B',
        t1: '#FFFFFF',
        t2: '#9A9AA8',
        t3: '#7E7E8C',
        t4: '#5A5A66',
        acc: '#00E28A',
        acc2: '#1FE795',
        acc3: '#00C074',
        accbg: 'rgba(0,226,138,.12)',
        gold: '#FFC24D',
        goldbg: 'rgba(255,194,77,.12)',
        red: '#FF4D5E',
        blue: '#4DA3FF',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'dis': ['40px', { lineHeight: '44px', letterSpacing: '-0.6px', fontWeight: '700' }],
        'dis2': ['32px', { lineHeight: '36px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'h1': ['24px', { lineHeight: '30px', letterSpacing: '-0.2px', fontWeight: '600' }],
        'h2': ['20px', { lineHeight: '26px', letterSpacing: '-0.1px', fontWeight: '600' }],
        'tl': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'tm': ['15px', { lineHeight: '22px', fontWeight: '500' }],
        'bl': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'bm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'bs': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'll': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'lm': ['12px', { lineHeight: '16px', letterSpacing: '0.2px', fontWeight: '500' }],
        'ls': ['11px', { lineHeight: '14px', letterSpacing: '0.4px', fontWeight: '500' }],
        'ov': ['11px', { lineHeight: '14px', letterSpacing: '0.9px', fontWeight: '600' }],
        'mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'mono-s': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      spacing: {
        '2xs': '2px',
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '32px',
        '5xl': '40px',
        '6xl': '48px',
        '7xl': '64px',
        '8xl': '80px',
        '9xl': '120px',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '28px',
        '3xl': '40px',
        'full': '999px',
      },
      boxShadow: {
        'e1': '0 1px 2px rgba(0,0,0,.40), 0 0 1px rgba(0,0,0,.24)',
        'e2': '0 4px 12px -2px rgba(0,0,0,.50), 0 1px 2px rgba(0,0,0,.30)',
        'e3': '0 12px 32px -6px rgba(0,0,0,.60), 0 2px 6px rgba(0,0,0,.35)',
        'e4': '0 24px 64px -12px rgba(0,0,0,.70), 0 4px 12px rgba(0,0,0,.40)',
        'player': '0 -8px 32px -8px rgba(0,0,0,.75)',
        'glow-acc': '0 6px 28px -2px rgba(0,226,138,.55)',
        'glow-gold': '0 4px 20px -4px rgba(255,194,77,.32)',
      },
    },
  },
  plugins: [
    plugin(function({ addUtilities }) {
      addUtilities({
        '.srow': {
          flexDirection: 'row',
          alignItems: 'center',
          paddingTop: 8,
          paddingBottom: 8,
          paddingLeft: 16,
          paddingRight: 16,
          minHeight: 56,
          gap: 12,
        },
        '.srow-on': {
          backgroundColor: '#0B0B0D',
        },
        '.seg-i': {
          flex: 1,
          paddingTop: 6,
          paddingBottom: 6,
          paddingLeft: 12,
          paddingRight: 12,
          borderRadius: 6,
          alignItems: 'center',
          justifyContent: 'center',
        },
        '.ib': {
          width: 40,
          height: 40,
          borderRadius: 999,
          alignItems: 'center',
          justifyContent: 'center',
        },
        '.playbtn': {
          width: 48,
          height: 48,
          borderRadius: 999,
          backgroundColor: '#00E28A',
          alignItems: 'center',
          justifyContent: 'center',
        },
        '.chip': {
          flexDirection: 'row',
          alignItems: 'center',
          paddingTop: 4,
          paddingBottom: 4,
          paddingLeft: 10,
          paddingRight: 10,
          borderRadius: 4,
          backgroundColor: '#17171B',
          gap: 4,
        },
        '.badge': {
          flexDirection: 'row',
          alignItems: 'center',
          paddingTop: 2,
          paddingBottom: 2,
          paddingLeft: 6,
          paddingRight: 6,
          borderRadius: 4,
          gap: 4,
        },
        '.field': {
          flexDirection: 'row',
          alignItems: 'center',
          paddingTop: 10,
          paddingBottom: 10,
          paddingLeft: 12,
          paddingRight: 12,
          borderRadius: 8,
          backgroundColor: '#111114',
          borderWidth: 1,
          borderColor: '#26262C',
          gap: 8,
        },
        '.art': {
          borderRadius: 12,
          overflow: 'hidden',
        },
        '.mini': {
          flexDirection: 'row',
          alignItems: 'center',
          height: 64,
          paddingLeft: 16,
          paddingRight: 16,
          backgroundColor: '#0B0B0D',
          borderTopWidth: 1,
          borderTopColor: '#1A1A1F',
          gap: 12,
        },
        '.mnav': {
          flexDirection: 'row',
          height: 64,
          backgroundColor: '#000000',
          borderTopWidth: 1,
          borderTopColor: '#1A1A1F',
        },
        '.src-local': {
          width: 18,
          height: 18,
          borderRadius: 4,
          backgroundColor: 'rgba(255,194,77,.12)',
          alignItems: 'center',
          justifyContent: 'center',
        },
        '.src-cloud': {
          width: 18,
          height: 18,
          borderRadius: 4,
          backgroundColor: 'rgba(0,226,138,.12)',
          alignItems: 'center',
          justifyContent: 'center',
        },
      });
    }),
  ],
}
